apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
spec:
  selector:
    app: todo-api
  ports:
    - protocol: TCP
      port: 8000       # Port exposed to the outside
      targetPort: 8000 # Port inside the container
  type: NodePort # Allows access on a local cluster (Kind)