name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - api-initial
      - dockerization
  pull_request:
    branches:
      - main
permissions:
  contents: read
  issues: write
  checks: write
  
jobs:
  build-test-sast:
    name: Build, Test & SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # ---------- SAST ----------
      - name: Run Bandit (Static Application Security Testing)
        run: |
          pip install bandit
          bandit -r app.py

      # ---------- Docker Build ----------
      - name: Build Docker image
        run: docker build -t devops-todo-api:${{ github.sha }} .


  dast-scan:
    name: DAST - OWASP ZAP
    runs-on: ubuntu-latest
    needs: build-test-sast

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t todo-api .

      - name: Run API container
        run: |
          docker run -d -p 8000:8000 --name todo-api todo-api
          sleep 10

      # ---------- DAST ----------
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:8000"
